# ==============================================================================
# OpenQuatt - Heatpump Controller Q Single WiFi compatibility entrypoint
# ==============================================================================
substitutions:
  alternate_dev_release_manifest_url: ""
  alternate_connection_url: ""
  alternate_topology_update_target: "false"
  alternate_topology_url: ""
  oq_tunnel_relay_host: "quatt.openheatpumps.nl"
  oq_tunnel_pump_secret: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"

# Correct global compilation configuration block according to ESPHome standards
esphome:
  build_flags:
    - "-DCONFIG_ESP_WEBSOCKET_CLIENT_ENABLE=1"
    - "-DSDKCONFIG_HAVE_TARGET_ESP_WEBSOCKET_CLIENT=1"

packages:
  unified_q_single: !include single.yaml
